### ISSUE TITLE
Invalid projection

### ISSUE THREAD

**Issue by neda-git** [matsim-vsp/matsim-python-tools#21]
Hello, I'm trying to run  geo = net.as_geo() but I get this error:

CRSError: Invalid projection: Atlantis: (Internal Proj Error: proj_create: unrecognized format / unknown name)

could you please let me know how can I solve it?

Thanks

**Comment by rakow** [comment]
"Atlantis" is not a valid coordinate system in terms of a EPSG code. Probably you need to put the correct coordinate system into the network attributes.
