### ISSUE TITLE
how to you get to the free form person attributes?

### ISSUE THREAD

**Issue by kainagel** [matsim-vsp/matsim-python-tools#5]
In xml, we have
```
	<person id="01067005_518">
		<attributes>
			<attribute name="age" class="java.lang.Integer">45</attribute>
			<attribute name="district" class="java.lang.String">Dresden</attribute>
			...
		</attributes>
	</person>
```
How to you get to, say, `age`?

**Comment by kainagel** [comment]
Ok, this I found myself:
```
for person, plan in plans:
    matsimAttributes = person.find('attributes')
    for matsimAttribute in matsimAttributes:
        if matsimAttribute.attrib['name'] == 'age':
            print( matsimAttribute.attrib, matsimAttribute.text )
```
Typical xml tree model where you get attributes as `attrib` and text as `text'; only for the elements it seems that they are there "by themselves".

Additionally confusing because of "attribute(s)" in the matsim naming scheme.

**Comment by billyc** [comment]
I'm glad you were able to solve this. But I am also wondering if we should change how the attributes are surfaced in the API? I don't want it to be incorrect but I also want users to feel comfortable in the Python environment.

The Python API to be as "pythonic" as possible, meaning that the fact the event file is XML shouldn't overtly influence the API itself: rather, the data should be available in a way that feels natural to Python users.
I will think this over! Thanks,
Billy
